"""Add promo_code and discount_percent to tariffs

Revision ID: 3084bd1d536e
Revises: 20260617_224832
Create Date: 2026-06-19 00:24:40.783025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3084bd1d536e'
down_revision: Union[str, Sequence[str], None] = '20260617_224832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_achievement_type'), 'achievements', ['achievement_type'], unique=False)
    op.create_index(op.f('ix_achievements_client_id'), 'achievements', ['client_id'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pinned_message_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('pdf_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by', sa.UUID(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_table('feature_flag_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flag_audit_id'), 'feature_flag_audit', ['id'], unique=False)
    op.create_table('feature_flag_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('requires_flag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requires_flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flag_dependencies_id'), 'feature_flag_dependencies', ['id'], unique=False)
    op.create_table('feature_flag_tenant_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flag_tenant_overrides_id'), 'feature_flag_tenant_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flag_tenant_overrides_tenant_id'), 'feature_flag_tenant_overrides', ['tenant_id'], unique=False)
    op.create_table('feature_flag_user_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flag_user_overrides_id'), 'feature_flag_user_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_feature_flag_user_overrides_user_id'), 'feature_flag_user_overrides', ['user_id'], unique=False)
    op.create_table('gamification_levels',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp_current', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('achievements_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_levels_client_id'), 'gamification_levels', ['client_id'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online_sessions',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('trainer_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_members',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_read_message_id', sa.String(length=36), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_member', 'chat_members', ['room_id', 'user_id', 'client_id'], unique=True)
    op.create_index(op.f('ix_chat_members_room_id'), 'chat_members', ['room_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('sender_client_id', sa.UUID(), nullable=True),
    sa.Column('sender_name', sa.String(length=200), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.String(length=36), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_msg_room_created', 'chat_messages', ['room_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_table('session_participants',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('watch_progress', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['online_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_participants_client_id'), 'session_participants', ['client_id'], unique=False)
    op.create_index(op.f('ix_session_participants_session_id'), 'session_participants', ['session_id'], unique=False)
    op.create_table('chat_message_reads',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('reader_user_id', sa.UUID(), nullable=True),
    sa.Column('reader_client_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reader_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['reader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_reads_message_id'), 'chat_message_reads', ['message_id'], unique=False)
    op.drop_table('license_keys')
    op.drop_index(op.f('ix_external_sync_logs_status'), table_name='external_sync_logs')
    op.drop_index(op.f('ix_external_sync_logs_system_type'), table_name='external_sync_logs')
    op.drop_table('external_sync_logs')
    op.drop_index(op.f('ix_access_logs_created_at'), table_name='access_logs')
    op.alter_column('cash_desk_sessions', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('cash_desk_sessions', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_cash_operations_payment_method'), table_name='cash_operations')
    op.drop_index(op.f('ix_cash_operations_reference_id'), table_name='cash_operations')
    op.drop_index(op.f('ix_cash_operations_reference_type'), table_name='cash_operations')
    op.drop_index(op.f('ix_devices_protocol'), table_name='devices')
    op.create_index(op.f('ix_dynamic_qr_codes_id'), 'dynamic_qr_codes', ['id'], unique=False)
    op.alter_column('employee_shifts', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('employee_shifts', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('employee_shifts', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_employee_shifts_id'), 'employee_shifts', ['id'], unique=False)
    op.alter_column('face_recognition_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('face_recognition_logs', 'face_template_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('face_recognition_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_face_recognition_logs_id'), 'face_recognition_logs', ['id'], unique=False)
    op.alter_column('face_templates', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('face_templates', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('face_templates', 'face_encoding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_face_templates_id'), 'face_templates', ['id'], unique=False)
    op.add_column('feature_flags', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('feature_flags', sa.Column('target_value', sa.JSON(), nullable=True))
    op.add_column('feature_flags', sa.Column('target_id', sa.Integer(), nullable=True))
    op.add_column('feature_flags', sa.Column('conditions', sa.JSON(), nullable=True))
    op.add_column('feature_flags', sa.Column('changed_by', sa.String(length=255), nullable=True))
    op.alter_column('feature_flags', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('feature_flags', 'flag_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('feature_flags', 'flag_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BOOLEAN', 'STRING', 'INTEGER', 'JSON', name='flagtype'),
               existing_nullable=False)
    op.alter_column('feature_flags', 'scope',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SYSTEM', 'MODULE', 'TENANT', 'USER', 'CANARY', name='flagscope'),
               existing_nullable=False)
    op.alter_column('feature_flags', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('feature_flags_flag_key_key'), 'feature_flags', type_='unique')
    op.create_index(op.f('ix_feature_flags_flag_key'), 'feature_flags', ['flag_key'], unique=True)
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_index(op.f('ix_license_activations_id'), 'license_activations', ['id'], unique=False)
    op.drop_constraint(op.f('licenses_license_key_key'), 'licenses', type_='unique')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.drop_index(op.f('ix_locker_sessions_lock_type'), table_name='locker_sessions')
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('receipts', 'fiscal_document_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_service_bookings_id'), 'service_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.add_column('tariffs', sa.Column('promo_code', sa.String(length=50), nullable=True))
    op.add_column('tariffs', sa.Column('discount_percent', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tariffs_promo_code'), 'tariffs', ['promo_code'], unique=False)
    op.alter_column('users', 'is_fired',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_video_alerts_id'), 'video_alerts', ['id'], unique=False)
    op.drop_index(op.f('ix_visits_processed_by_user_id'), table_name='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_visits_processed_by_user_id'), 'visits', ['processed_by_user_id'], unique=False)
    op.drop_index(op.f('ix_video_alerts_id'), table_name='video_alerts')
    op.alter_column('users', 'is_fired',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_tariffs_promo_code'), table_name='tariffs')
    op.drop_column('tariffs', 'discount_percent')
    op.drop_column('tariffs', 'promo_code')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_service_bookings_id'), table_name='service_bookings')
    op.alter_column('receipts', 'fiscal_document_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('payments', 'paid_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_locker_sessions_lock_type'), 'locker_sessions', ['lock_type'], unique=False)
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=False)
    op.create_unique_constraint(op.f('licenses_license_key_key'), 'licenses', ['license_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_license_activations_id'), table_name='license_activations')
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_flag_key'), table_name='feature_flags')
    op.create_unique_constraint(op.f('feature_flags_flag_key_key'), 'feature_flags', ['flag_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('feature_flags', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('feature_flags', 'scope',
               existing_type=sa.Enum('SYSTEM', 'MODULE', 'TENANT', 'USER', 'CANARY', name='flagscope'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('feature_flags', 'flag_type',
               existing_type=sa.Enum('BOOLEAN', 'STRING', 'INTEGER', 'JSON', name='flagtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('feature_flags', 'flag_key',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('feature_flags', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('feature_flags', 'changed_by')
    op.drop_column('feature_flags', 'conditions')
    op.drop_column('feature_flags', 'target_id')
    op.drop_column('feature_flags', 'target_value')
    op.drop_column('feature_flags', 'name')
    op.drop_index(op.f('ix_face_templates_id'), table_name='face_templates')
    op.alter_column('face_templates', 'face_encoding',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('face_templates', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('face_templates', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index(op.f('ix_face_recognition_logs_id'), table_name='face_recognition_logs')
    op.alter_column('face_recognition_logs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('face_recognition_logs', 'face_template_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('face_recognition_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index(op.f('ix_employee_shifts_id'), table_name='employee_shifts')
    op.alter_column('employee_shifts', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('employee_shifts', 'employee_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('employee_shifts', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_index(op.f('ix_dynamic_qr_codes_id'), table_name='dynamic_qr_codes')
    op.create_index(op.f('ix_devices_protocol'), 'devices', ['protocol'], unique=False)
    op.create_index(op.f('ix_cash_operations_reference_type'), 'cash_operations', ['reference_type'], unique=False)
    op.create_index(op.f('ix_cash_operations_reference_id'), 'cash_operations', ['reference_id'], unique=False)
    op.create_index(op.f('ix_cash_operations_payment_method'), 'cash_operations', ['payment_method'], unique=False)
    op.alter_column('cash_desk_sessions', 'closed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('cash_desk_sessions', 'opened_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_access_logs_created_at'), 'access_logs', ['created_at'], unique=False)
    op.create_table('external_sync_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('system_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('external_sync_logs_pkey'))
    )
    op.create_index(op.f('ix_external_sync_logs_system_type'), 'external_sync_logs', ['system_type'], unique=False)
    op.create_index(op.f('ix_external_sync_logs_status'), 'external_sync_logs', ['status'], unique=False)
    op.create_table('license_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('license_type', sa.VARCHAR(length=50), server_default=sa.text("'pro'::character varying"), autoincrement=False, nullable=True),
    sa.Column('max_users', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True),
    sa.Column('max_clients', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=True),
    sa.Column('max_terminals', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('license_keys_pkey')),
    sa.UniqueConstraint('key', name=op.f('license_keys_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_chat_message_reads_message_id'), table_name='chat_message_reads')
    op.drop_table('chat_message_reads')
    op.drop_index(op.f('ix_session_participants_session_id'), table_name='session_participants')
    op.drop_index(op.f('ix_session_participants_client_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_index('idx_chat_msg_room_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_members_room_id'), table_name='chat_members')
    op.drop_index('idx_chat_member', table_name='chat_members')
    op.drop_table('chat_members')
    op.drop_table('online_sessions')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_gamification_levels_client_id'), table_name='gamification_levels')
    op.drop_table('gamification_levels')
    op.drop_index(op.f('ix_feature_flag_user_overrides_user_id'), table_name='feature_flag_user_overrides')
    op.drop_index(op.f('ix_feature_flag_user_overrides_id'), table_name='feature_flag_user_overrides')
    op.drop_table('feature_flag_user_overrides')
    op.drop_index(op.f('ix_feature_flag_tenant_overrides_tenant_id'), table_name='feature_flag_tenant_overrides')
    op.drop_index(op.f('ix_feature_flag_tenant_overrides_id'), table_name='feature_flag_tenant_overrides')
    op.drop_table('feature_flag_tenant_overrides')
    op.drop_index(op.f('ix_feature_flag_dependencies_id'), table_name='feature_flag_dependencies')
    op.drop_table('feature_flag_dependencies')
    op.drop_index(op.f('ix_feature_flag_audit_id'), table_name='feature_flag_audit')
    op.drop_table('feature_flag_audit')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_achievements_client_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_achievement_type'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
